CREATE TABLE todos (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT
);

INSERT INTO todos (title, description)
VALUES
  ('Dog', 'Walk the dog'),
  ('Cat', 'Bathe the cat'),
  ('Fish', 'Feed the fish');